#! /bin/sh

set -e

SBCL_SOURCE_LOCATION=/usr/local/src/sbcl-${SBCL_VERSION}
PATCHES_LOCATION=${SBCL_SOURCE_LOCATION}/patches

cd "${SBCL_SOURCE_LOCATION}"

if [ -d "${PATCHES_LOCATION}" ]; then
    for p in "${PATCHES_LOCATION}"/*.patch; do patch -p1 < "$p"; done
fi

sh make.sh
sh install.sh

rm -f /usr/local/bin/sbcl.old /usr/local/lib/sbcl/sbcl.core.old
