os: linux
dist: focal
language: minimal

env:
  global:
    DOCKER_BUILDKIT: "1"
    DOCKER_CLI_EXPERIMENTAL: "enabled"

services:
  - docker

before_script:
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - docker info

script:
  - docker pull --platform "$DOCKER_PLATFORM" "$IMAGE_NAME:$IMAGE_TAG" || true
  - docker build --platform "$DOCKER_PLATFORM" --pull -t "$IMAGE_NAME:$IMAGE_TAG" --cache-from "$IMAGE_NAME:$IMAGE_TAG" --build-arg BUILDKIT_INLINE_CACHE=1 "$BUILD_CONTEXT"

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push "$IMAGE_NAME:$IMAGE_TAG"

jobs:
  include:
    # Alpine 3.12
    - arch: amd64
      env:
        BUILD_CONTEXT: images/alpine/3.12/amd64
        DOCKER_PLATFORM: linux/amd64
        IMAGE_NAME: mitmersamd64/sbcl
        IMAGE_TAG: 2.0.9-alpine3.12
    - arch: arm64
      env:
        BUILD_CONTEXT: images/alpine/3.12/arm64
        DOCKER_PLATFORM: linux/arm64/v8
        IMAGE_NAME: mitmersarm64v8/sbcl
        IMAGE_TAG: 2.0.9-alpine3.12
    - arch: arm64
      env:
        BUILD_CONTEXT: images/alpine/3.12/arm32v7
        DOCKER_PLATFORM: linux/arm/v7
        IMAGE_NAME: mitmersarm32v7/sbcl
        IMAGE_TAG: 2.0.9-alpine3.12
    # Alpine 3.11
    - arch: amd64
      env:
        BUILD_CONTEXT: images/alpine/3.11/amd64
        DOCKER_PLATFORM: linux/amd64
        IMAGE_NAME: mitmersamd64/sbcl
        IMAGE_TAG: 2.0.9-alpine3.11
    - arch: arm64
      env:
        BUILD_CONTEXT: images/alpine/3.11/arm64
        DOCKER_PLATFORM: linux/arm64/v8
        IMAGE_NAME: mitmersarm64v8/sbcl
        IMAGE_TAG: 2.0.9-alpine3.11
    - arch: arm64
      env:
        BUILD_CONTEXT: images/alpine/3.11/arm32v7
        DOCKER_PLATFORM: linux/arm/v7
        IMAGE_NAME: mitmersarm32v7/sbcl
        IMAGE_TAG: 2.0.9-alpine3.11
    # Debian Buster
    - arch: amd64
      env:
        BUILD_CONTEXT: images/debian/buster/amd64
        DOCKER_PLATFORM: linux/amd64
        IMAGE_NAME: mitmersamd64/sbcl
        IMAGE_TAG: 2.0.9-debian-buster
    - arch: arm64
      env:
        BUILD_CONTEXT: images/debian/buster/arm64
        DOCKER_PLATFORM: linux/arm64/v8
        IMAGE_NAME: mitmersarm64v8/sbcl
        IMAGE_TAG: 2.0.9-debian-buster
    - arch: arm64
      env:
        BUILD_CONTEXT: images/debian/buster/arm32v7
        DOCKER_PLATFORM: linux/arm/v7
        IMAGE_NAME: mitmersarm32v7/sbcl
        IMAGE_TAG: 2.0.9-debian-buster
    # Debian Stretch
    - arch: amd64
      env:
        BUILD_CONTEXT: images/debian/stretch/amd64
        DOCKER_PLATFORM: linux/amd64
        IMAGE_NAME: mitmersamd64/sbcl
        IMAGE_TAG: 2.0.9-debian-stretch
    - arch: arm64
      env:
        BUILD_CONTEXT: images/debian/stretch/arm64
        DOCKER_PLATFORM: linux/arm64/v8
        IMAGE_NAME: mitmersarm64v8/sbcl
        IMAGE_TAG: 2.0.9-debian-stretch
    - arch: arm64
      env:
        BUILD_CONTEXT: images/debian/stretch/arm32v7
        DOCKER_PLATFORM: linux/arm/v7
        IMAGE_NAME: mitmersarm32v7/sbcl
        IMAGE_TAG: 2.0.9-debian-stretch
    # Ubuntu Focal
    - arch: amd64
      env:
        BUILD_CONTEXT: images/ubuntu/focal/amd64
        DOCKER_PLATFORM: linux/amd64
        IMAGE_NAME: mitmersamd64/sbcl
        IMAGE_TAG: 2.0.9-ubuntu-focal
    - arch: arm64
      env:
        BUILD_CONTEXT: images/ubuntu/focal/arm64
        DOCKER_PLATFORM: linux/arm64/v8
        IMAGE_NAME: mitmersarm64v8/sbcl
        IMAGE_TAG: 2.0.9-ubuntu-focal
    - arch: arm64
      before_install:
        - sudo apt-get remove -y docker docker-engine docker.io containerd runc
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      env:
        BUILD_CONTEXT: images/ubuntu/focal/arm32v7
        DOCKER_PLATFORM: linux/arm/v7
        IMAGE_NAME: mitmersarm32v7/sbcl
        IMAGE_TAG: 2.0.9-ubuntu-focal
    # Ubuntu Bionic
    - arch: amd64
      env:
        BUILD_CONTEXT: images/ubuntu/bionic/amd64
        DOCKER_PLATFORM: linux/amd64
        IMAGE_NAME: mitmersamd64/sbcl
        IMAGE_TAG: 2.0.9-ubuntu-bionic
    - arch: arm64
      env:
        BUILD_CONTEXT: images/ubuntu/bionic/arm64
        DOCKER_PLATFORM: linux/arm64/v8
        IMAGE_NAME: mitmersarm64v8/sbcl
        IMAGE_TAG: 2.0.9-ubuntu-bionic
    - arch: arm64
      env:
        BUILD_CONTEXT: images/ubuntu/bionic/arm32v7
        DOCKER_PLATFORM: linux/arm/v7
        IMAGE_NAME: mitmersarm32v7/sbcl
        IMAGE_TAG: 2.0.9-ubuntu-bionic
