os: linux
dist: focal
language: minimal

env:
  global:
    DOCKER_BUILDKIT: "1"
    DOCKER_CLI_EXPERIMENTAL: "enabled"
    IMAGE_NAME: daewoktest/sbcl

services:
  - docker

before_install:
  - docker info

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

jobs:
  include:
    - script:
        - docker pull debian:buster
        - docker pull $IMAGE_NAME:latest || true
        - docker build -t $IMAGE_NAME:latest --cache-from $IMAGE_NAME:latest --build-arg BUILDKIT_INLINE_CACHE=1 images/debian/buster/amd64
      after_success:
        - docker push $IMAGE_NAME:latest
