os: linux
dist: focal
language: shell


env:
  global:
    BUILD_SCRIPT: cl-docker-images-build/cl-docker-images-build
    DOCKER_BUILDKIT: "1"
    DOCKER_CLI_EXPERIMENTAL: "enabled"

stages:
  - name: build
  - name: deploy
    if: branch = master

services:
  - docker

before_install:
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - docker info
  - |
    # Log in earlier, to hopefully avoid running into Docker Hub's new pull
    # limits.
    if [ -n "$DOCKER_PASSWORD" ]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    fi
  - |
    if [ "$TRAVIS_BRANCH" = "master" ]; then
      BUILD_TAG_SUFFIX="-tmp-master"
    else
      BUILD_TAG_SUFFIX="-tmp"
    fi
    export BUILD_TAG_SUFFIX

_nonnightly: &nonnightly
  if: (NOT (type = cron) AND NOT (branch =~ ^nightly-.*$))

_nightly: &nightly
  allow_failures:
    if: NOT (type = cron)
  before_script:
    - mkdir tmp
    - cd tmp
    - git clone https://github.com/sbcl/sbcl.git
    - cd sbcl
    - export EXTRA_BUILDARGS="--build-arg ref=$(git rev-parse HEAD)"
    - cd ../..
    - rm -rf tmp

_nonfancy_job: &nonfancy_job
  stage: build
  script:
    # Pull the previous images
    - $BUILD_SCRIPT pull
    - $BUILD_SCRIPT -t build pull
    # Build the stock image
    - $BUILD_SCRIPT build
    # Tag this image as the build image refers to it by its non-arch specific
    # name
    - $BUILD_SCRIPT tag_for_next_variant
    # Build the build variant of the image
    - $BUILD_SCRIPT -t build build
  after_success: |
    if [ -n "$DOCKER_PASSWORD" ]; then
      $BUILD_SCRIPT push_build_image
      $BUILD_SCRIPT -t build push_build_image
    fi

_fancy_job: &fancy_job
  stage: build
  script:
    # Pull the previous images
    - $BUILD_SCRIPT -t fancy pull
    # Build the fancy image
    - $BUILD_SCRIPT -t fancy build
  after_success: |
    if [ -n "$DOCKER_PASSWORD" ]; then
      $BUILD_SCRIPT -t fancy push_build_image
    fi

jobs:
  include:
    # Regular images
    # Alpine 3.12
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: alpine
        OS_VERSION: "3.12"
      <<: [*nonfancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: alpine
        OS_VERSION: "3.12"
      <<: [*nonfancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: alpine
        OS_VERSION: "3.12"
      <<: [*nonfancy_job, *nonnightly]
    # Alpine 3.11
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: alpine
        OS_VERSION: "3.11"
      <<: [*nonfancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: alpine
        OS_VERSION: "3.11"
      <<: [*nonfancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: alpine
        OS_VERSION: "3.11"
      <<: [*nonfancy_job, *nonnightly]
    # Debian Buster
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: debian
        OS_VERSION: "buster"
      <<: [*nonfancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: debian
        OS_VERSION: "buster"
      <<: [*nonfancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: debian
        OS_VERSION: "buster"
      <<: [*nonfancy_job, *nonnightly]
    # Debian Stretch
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: debian
        OS_VERSION: "stretch"
      <<: [*nonfancy_job, *nonnightly]
    - arch: arm64
      install:
        - unset DOCKER_BUILDKIT
        - sudo apt-get remove -y docker docker.io containerd runc
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        - sudo apt-get upgrade -y
      env:
        ARCH: arm64
        OS_NAME: debian
        OS_VERSION: "stretch"
      <<: [*nonfancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: debian
        OS_VERSION: "stretch"
      <<: [*nonfancy_job, *nonnightly]
    # Ubuntu Focal
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: ubuntu
        OS_VERSION: "focal"
      <<: [*nonfancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: ubuntu
        OS_VERSION: "focal"
      <<: [*nonfancy_job, *nonnightly]
    - arch: arm64
      install:
        - unset DOCKER_BUILDKIT
        - sudo apt-get remove -y docker docker.io containerd runc
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      env:
        ARCH: arm32v7
        OS_NAME: ubuntu
        OS_VERSION: "focal"
      <<: [*nonfancy_job, *nonnightly]
    # Ubuntu Bionic
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: ubuntu
        OS_VERSION: "bionic"
      <<: [*nonfancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: ubuntu
        OS_VERSION: "bionic"
      <<: [*nonfancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: ubuntu
        OS_VERSION: "bionic"
      <<: [*nonfancy_job, *nonnightly]

    # Fancy images
    # Alpine 3.12
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: alpine
        OS_VERSION: "3.12"
      <<: [*fancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: alpine
        OS_VERSION: "3.12"
      <<: [*fancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: alpine
        OS_VERSION: "3.12"
      <<: [*fancy_job, *nonnightly]
    # Alpine 3.11
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: alpine
        OS_VERSION: "3.11"
      <<: [*fancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: alpine
        OS_VERSION: "3.11"
      <<: [*fancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: alpine
        OS_VERSION: "3.11"
      <<: [*fancy_job, *nonnightly]
    # Debian Buster
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: debian
        OS_VERSION: "buster"
      <<: [*fancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: debian
        OS_VERSION: "buster"
      <<: [*fancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: debian
        OS_VERSION: "buster"
      <<: [*fancy_job, *nonnightly]
    # Debian Stretch
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: debian
        OS_VERSION: "stretch"
      <<: [*fancy_job, *nonnightly]
    - arch: arm64
      install:
        - unset DOCKER_BUILDKIT
        - sudo apt-get remove -y docker docker.io containerd runc
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        - sudo apt-get upgrade -y
      env:
        ARCH: arm64
        OS_NAME: debian
        OS_VERSION: "stretch"
      <<: [*fancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: debian
        OS_VERSION: "stretch"
      <<: [*fancy_job, *nonnightly]
    # Ubuntu Focal
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: ubuntu
        OS_VERSION: "focal"
      <<: [*fancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: ubuntu
        OS_VERSION: "focal"
      <<: [*fancy_job, *nonnightly]
    - arch: arm64
      install:
        - unset DOCKER_BUILDKIT
        - sudo apt-get remove -y docker docker.io containerd runc
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      env:
        ARCH: arm32v7
        OS_NAME: ubuntu
        OS_VERSION: "focal"
      <<: [*fancy_job, *nonnightly]
    # Ubuntu Bionic
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: ubuntu
        OS_VERSION: "bionic"
      <<: [*fancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: ubuntu
        OS_VERSION: "bionic"
      <<: [*fancy_job, *nonnightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: ubuntu
        OS_VERSION: "bionic"
      <<: [*fancy_job, *nonnightly]

    # Nightly jobs
    # Alpine 3.12
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: alpine
        OS_VERSION: "3.12"
        VERSION: nightly
      <<: [*nonfancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: alpine
        OS_VERSION: "3.12"
        VERSION: nightly
      <<: [*nonfancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: alpine
        OS_VERSION: "3.12"
        VERSION: nightly
      <<: [*nonfancy_job, *nightly]
    # Alpine 3.11
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: alpine
        OS_VERSION: "3.11"
        VERSION: nightly
      <<: [*nonfancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: alpine
        OS_VERSION: "3.11"
        VERSION: nightly
      <<: [*nonfancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: alpine
        OS_VERSION: "3.11"
        VERSION: nightly
      <<: [*nonfancy_job, *nightly]
    # Debian Buster
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: debian
        OS_VERSION: "buster"
        VERSION: nightly
      <<: [*nonfancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: debian
        OS_VERSION: "buster"
        VERSION: nightly
      <<: [*nonfancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: debian
        OS_VERSION: "buster"
        VERSION: nightly
      <<: [*nonfancy_job, *nightly]
    # Debian Stretch
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: debian
        OS_VERSION: "stretch"
        VERSION: nightly
      <<: [*nonfancy_job, *nightly]
    - arch: arm64
      install:
        - unset DOCKER_BUILDKIT
        - sudo apt-get remove -y docker docker.io containerd runc
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        - sudo apt-get upgrade -y
      env:
        ARCH: arm64
        OS_NAME: debian
        OS_VERSION: "stretch"
        VERSION: nightly
      <<: [*nonfancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: debian
        OS_VERSION: "stretch"
        VERSION: nightly
      <<: [*nonfancy_job, *nightly]
    # Ubuntu Focal
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: ubuntu
        OS_VERSION: "focal"
        VERSION: nightly
      <<: [*nonfancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: ubuntu
        OS_VERSION: "focal"
        VERSION: nightly
      <<: [*nonfancy_job, *nightly]
    - arch: arm64
      install:
        - unset DOCKER_BUILDKIT
        - sudo apt-get remove -y docker docker.io containerd runc
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      env:
        ARCH: arm32v7
        OS_NAME: ubuntu
        OS_VERSION: "focal"
        VERSION: nightly
      <<: [*nonfancy_job, *nightly]
    # Ubuntu Bionic
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: ubuntu
        OS_VERSION: "bionic"
        VERSION: nightly
      <<: [*nonfancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: ubuntu
        OS_VERSION: "bionic"
        VERSION: nightly
      <<: [*nonfancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: ubuntu
        OS_VERSION: "bionic"
        VERSION: nightly
      <<: [*nonfancy_job, *nightly]

    # Fancy images
    # Alpine 3.12
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: alpine
        OS_VERSION: "3.12"
        VERSION: nightly
      <<: [*fancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: alpine
        OS_VERSION: "3.12"
        VERSION: nightly
      <<: [*fancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: alpine
        OS_VERSION: "3.12"
        VERSION: nightly
      <<: [*fancy_job, *nightly]
    # Alpine 3.11
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: alpine
        OS_VERSION: "3.11"
        VERSION: nightly
      <<: [*fancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: alpine
        OS_VERSION: "3.11"
        VERSION: nightly
      <<: [*fancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: alpine
        OS_VERSION: "3.11"
        VERSION: nightly
      <<: [*fancy_job, *nightly]
    # Debian Buster
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: debian
        OS_VERSION: "buster"
        VERSION: nightly
      <<: [*fancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: debian
        OS_VERSION: "buster"
        VERSION: nightly
      <<: [*fancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: debian
        OS_VERSION: "buster"
        VERSION: nightly
      <<: [*fancy_job, *nightly]
    # Debian Stretch
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: debian
        OS_VERSION: "stretch"
        VERSION: nightly
      <<: [*fancy_job, *nightly]
    - arch: arm64
      install:
        - unset DOCKER_BUILDKIT
        - sudo apt-get remove -y docker docker.io containerd runc
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        - sudo apt-get upgrade -y
      env:
        ARCH: arm64
        OS_NAME: debian
        OS_VERSION: "stretch"
        VERSION: nightly
      <<: [*fancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: debian
        OS_VERSION: "stretch"
        VERSION: nightly
      <<: [*fancy_job, *nightly]
    # Ubuntu Focal
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: ubuntu
        OS_VERSION: "focal"
        VERSION: nightly
      <<: [*fancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: ubuntu
        OS_VERSION: "focal"
        VERSION: nightly
      <<: [*fancy_job, *nightly]
    - arch: arm64
      install:
        - unset DOCKER_BUILDKIT
        - sudo apt-get remove -y docker docker.io containerd runc
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      env:
        ARCH: arm32v7
        OS_NAME: ubuntu
        OS_VERSION: "focal"
        VERSION: nightly
      <<: [*fancy_job, *nightly]
    # Ubuntu Bionic
    - arch: amd64
      env:
        ARCH: amd64
        OS_NAME: ubuntu
        OS_VERSION: "bionic"
        VERSION: nightly
      <<: [*fancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm64
        OS_NAME: ubuntu
        OS_VERSION: "bionic"
        VERSION: nightly
      <<: [*fancy_job, *nightly]
    - arch: arm64
      env:
        ARCH: arm32v7
        OS_NAME: ubuntu
        OS_VERSION: "bionic"
        VERSION: nightly
      <<: [*fancy_job, *nightly]
    - arch: amd64
      stage: deploy
      env:
        VERSION: nightly
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        # First, download all the nightly builds, retag them, and push them to
        # the arch specific repos
        - ./scripts/retag-tmp-master-images
        # Next, create and push all the linux manifests
        - ./scripts/release-linux-manifests
        # Last, release shared manifests
        - ./scripts/release-shared-manifests
