os: linux
dist: focal
language: minimal

env:
  global:
    DOCKER_BUILDKIT: "1"
    DOCKER_CLI_EXPERIMENTAL: "enabled"

services:
  - docker

before_install:
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart

before_script:
  - docker info

script:
  - docker pull --platform "$DOCKER_PLATFORM" "$BASE_IMAGE"
  - docker pull --platform "$DOCKER_PLATFORM" "$IMAGE_NAME:$IMAGE_TAG" || true
  - docker build --platform "$DOCKER_PLATFORM" -t "$IMAGE_NAME:$IMAGE_TAG" --cache-from "$IMAGE_NAME:$IMAGE_TAG" --build-arg BUILDKIT_INLINE_CACHE=1 "$BUILD_CONTEXT"

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push "$IMAGE_NAME:$IMAGE_TAG"

jobs:
  include:
    - arch: amd64
      env:
        BASE_IMAGE: debian:buster
        BUILD_CONTEXT: images/debian/buster/amd64
        DOCKER_PLATFORM: linux/amd64
        IMAGE_NAME: mitmersamd64/sbcl
        IMAGE_TAG: 2.0.9-debian-buster
    - arch: arm64
      env:
        BASE_IMAGE: debian:buster
        BUILD_CONTEXT: images/debian/buster/arm64
        DOCKER_PLATFORM: linux/arm64/v8
        IMAGE_NAME: mitmersarm64v8/sbcl
        IMAGE_TAG: 2.0.9-debian-buster
    - arch: arm64
      env:
        BASE_IMAGE: debian:buster
        BUILD_CONTEXT: images/debian/buster/arm32v7
        DOCKER_PLATFORM: linux/arm/v7
        IMAGE_NAME: mitmersarm32v7/sbcl
        IMAGE_TAG: 2.0.9-debian-buster
