FROM alpine:3.10

LABEL maintainer="etimmons@mit.edu"

ENV SBCL_ARCH=arm

WORKDIR /usr/local/src/

# hadolint ignore=DL3003,DL3018
RUN set -x \
    && import_key() { \
         gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$1" \
         || gpg --batch --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys "$1" \
         || gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$1" \
         || gpg --batch --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys "$1" \
         || gpg --batch --keyserver pgp.mit.edu --recv-keys "$1"; \
       } \
    && download_and_validate_hashes() { \
         curl -L "https://downloads.sourceforge.net/project/sbcl/sbcl/${1}/sbcl-${1}-crhodes.asc" > "sbcl-${1}-crhodes.asc" \
         && gpg --batch --verify "sbcl-${1}-crhodes.asc" \
         && gpg --batch --decrypt "sbcl-${1}-crhodes.asc" > "sbcl-${1}-crhodes.txt"; \
       } \
    && apk add --no-cache ca-certificates curl openssl make gcc musl-dev linux-headers gnupg ecl \
                          gmp-dev g++ libffi-dev musl-dev gc gc-dev linux-headers ecl-dev git ed

COPY test-entrypoint.sh /usr/local/bin/test-entrypoint.sh

VOLUME /patches
VOLUME /sbcl
WORKDIR /sbcl

ENTRYPOINT ["/usr/local/bin/test-entrypoint.sh"]
