FROM alpine:3.12

LABEL maintainer="etimmons@mit.edu"

ENV SBCL_ARCH=arm

WORKDIR /usr/local/src/

# hadolint ignore=DL3018
RUN set -x \
    && apk add --no-cache ca-certificates curl openssl make gcc musl-dev linux-headers gnupg \
                          gmp-dev g++ libffi-dev git ed \
    && apk add --no-cache sbcl --repository http://dl-3.alpinelinux.org/alpine/edge/community/

COPY test-sbcl /usr/local/bin/test-sbcl

VOLUME /patches
VOLUME /sbcl
WORKDIR /sbcl
