#! /bin/sh

set -e

SBCL_SOURCE_LOCATION=/c/sbcl-${SBCL_VERSION}
PATCHES_LOCATION=${SBCL_SOURCE_LOCATION}/patches

cd "${SBCL_SOURCE_LOCATION}"

if [ -d "${PATCHES_LOCATION}" ]; then
  for p in "${PATCHES_LOCATION}"/*.patch; do
    echo "Applying patch $p"
    patch -p1 < "$p"
  done
fi

sh ./make.sh
export WIX="/c/wix"
sh ./make-windows-installer.sh
