#!/bin/bash

set -x

pull_retag_and_push_archs() {
  for variant in "" -fancy -build; do
    for arch in amd64 arm32v7 arm64v8; do
      docker pull "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-$1$2$variant-tmp-master"
      docker tag "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-$1$2$variant-tmp-master" "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-$1$2$variant"
      docker push "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-$1$2$variant"
    done
  done
}

# Alpine
for os_version in 3.12 3.11; do
  pull_retag_and_push_archs alpine $os_version
done
for variant in "" -fancy -build; do
  for arch in amd64 arm32v7 arm64v8; do
    docker tag "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-alpine$ALPINE_LATEST$variant" "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-alpine$variant"
    docker push "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-alpine$variant"
    if [ "$VERSION" = "$LATEST_VERSION" ]; then
      docker tag "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-alpine$ALPINE_LATEST$variant" "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:latest-alpine$variant"
      docker push "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:latest-alpine$variant"
      docker tag "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-alpine$ALPINE_LATEST$variant" "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:alpine$variant"
      docker push "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:alpine$variant"
    fi
  done
done

# Debian
for os_version in -buster -stretch; do
  pull_retag_and_push_archs debian $os_version
done
for variant in "" -fancy -build; do
  for arch in amd64 arm32v7 arm64v8; do
    docker tag "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-debian-$DEBIAN_LATEST$variant" "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-debian$variant"
    docker push "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-debian$variant"
    docker tag "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-debian-$DEBIAN_LATEST$variant" "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION$variant"
    docker push "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION$variant"
    if [ "$VERSION" = "$LATEST_VERSION" ]; then
      docker tag "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-debian-$DEBIAN_LATEST$variant" "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:latest-debian$variant"
      docker push "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:latest-debian$variant"
      docker tag "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-debian-$DEBIAN_LATEST$variant" "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:debian$variant"
      docker push "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:debian$variant"
    fi
  done
done

# Ubuntu
for os_version in -focal -bionic; do
  pull_retag_and_push_archs ubuntu $os_version
done
for variant in "" -fancy -build; do
  for arch in amd64 arm32v7 arm64v8; do
    docker tag "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-ubuntu-$UBUNTU_LATEST$variant" "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-ubuntu$variant"
    docker push "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-ubuntu$variant"
    if [ "$VERSION" = "$LATEST_VERSION" ]; then
      docker tag "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-ubuntu-$UBUNTU_LATEST$variant" "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:latest-ubuntu$variant"
      docker push "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:latest-ubuntu$variant"
      docker tag "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:$VERSION-ubuntu-$UBUNTU_LATEST$variant" "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:ubuntu$variant"
      docker push "${IMAGE_BUILD_NAMESPACE}$arch/$IMAGE_NAME:ubuntu$variant"
    fi
  done
done
