FROM alpine:3.11

LABEL maintainer="etimmons@mit.edu"

ENV SBCL_ARCH=arm64

WORKDIR /usr/local/src/

# hadolint ignore=DL3003,DL3018
RUN set -x \
    && download_and_install_ecl() { \
         curl -L "https://common-lisp.net/project/ecl/static/files/release/ecl-20.4.24.tgz" > ecl.tgz \
         && tar xf ecl.tgz \
         && cd ecl-20.4.24 \
         && ./configure --disable-manual --enable-boehm=included \
         && make "-j$(nproc)" \
         && make install \
         && cd /usr/local/src; \
    } \
    && apk add --no-cache ca-certificates curl openssl make gcc musl-dev linux-headers gnupg \
                          gmp-dev g++ libffi-dev git ed \
    && download_and_install_ecl

COPY test-sbcl /usr/local/bin/test-sbcl

VOLUME /patches
VOLUME /sbcl
WORKDIR /sbcl
